services:
  postgres:
    image: postgres:16
    container_name: padel_club_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - padel_data:/var/lib/postgresql/data  # los datos persisten aunque pares el contenedor

volumes:
  padel_data: