spring.application.name=padel-club-api

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/padel_club
spring.datasource.username=padel_user
spring.datasource.password=padel_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security
jwt.secret=8f01cb458a46a1fdc58e3a41084e32cc893c462524b79cb8872dbc6bd2ed5a2f
jwt.expiration=900
refresh_token.expiration=604800

# Cambiá solo esta línea para cambiar de proveedor
email.provider=gmail
email.from=diagonal@gmail.com

# Config Gmail
google.secret="tu_google_secret"
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tucuenta@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Config SendGrid (dejalo aunque no lo uses, no rompe nada si las props no se leen)
# sendgrid.api-key=SG.xxxx
# sendgrid.verify-email-template-id=d-xxxx
# sendgrid.reset-password-template-id=d-xxxx