-- Tabla canchas
CREATE TABLE IF NOT EXISTS public.canchas (
    id integer NOT NULL,
    descripcion character varying(300) NOT NULL,
    numero integer NOT NULL
);

ALTER TABLE public.canchas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.canchas_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.canchas ADD CONSTRAINT canchas_pkey PRIMARY KEY (id);

-- Tabla usuarios
CREATE TABLE IF NOT EXISTS public.usuarios (
    id bigint NOT NULL,
    apellido character varying(50),
    email character varying(100) NOT NULL,
    email_verificado boolean NOT NULL,
    enabled boolean NOT NULL,
    nombre character varying(50),
    password_hash character varying(255),
    provider character varying(20) NOT NULL,
    rol character varying(20) NOT NULL,
    telefono character varying(20),
    terms_accepted boolean NOT NULL,
    terms_accepted_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT usuarios_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT usuarios_rol_check CHECK (((rol)::text = ANY ((ARRAY['CLIENTE'::character varying, 'EMPLEADO'::character varying, 'ADMIN'::character varying, 'PROFESOR'::character varying])::text[])))
);

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.usuarios ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.usuarios ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);

-- Tabla clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id bigint NOT NULL,
    categoria smallint,
    posicion smallint,
    usuario_id bigint NOT NULL,
    CONSTRAINT clientes_categoria_check CHECK (((categoria >= 0) AND (categoria <= 7))),
    CONSTRAINT clientes_posicion_check CHECK (((posicion >= 0) AND (posicion <= 2)))
);

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.clientes ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.clientes ADD CONSTRAINT uk96x1n5ut15ns1xhkm87y7qhnd UNIQUE (usuario_id);
ALTER TABLE ONLY public.clientes ADD CONSTRAINT fkk6iwsq3kts1bblivkjy6epajx FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

-- Tabla configuracion
CREATE TABLE IF NOT EXISTS public.configuracion (
    id bigint NOT NULL,
    duracion_maxima_turno integer NOT NULL,
    duracion_minima_turno integer NOT NULL,
    monto_reserva real NOT NULL,
    monto_x_media_hora real NOT NULL,
    porcentaje_senia real NOT NULL
);

ALTER TABLE ONLY public.configuracion ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id);

-- Tabla dias
CREATE TABLE IF NOT EXISTS public.dias (
    id integer NOT NULL,
    dia character varying(10) NOT NULL,
    horario_fin time(0) without time zone NOT NULL,
    horario_inicio time(0) without time zone NOT NULL,
    configuracion_general_id bigint NOT NULL
);

ALTER TABLE public.dias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dias_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.dias ADD CONSTRAINT dias_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dias ADD CONSTRAINT fkkrv3h0s8yd20d400y7wxdfcho FOREIGN KEY (configuracion_general_id) REFERENCES public.configuracion(id);

-- Tabla refresh_tokens
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id bigint NOT NULL,
    fecha_expiracion timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    usuario_id bigint
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_tokens ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);
ALTER TABLE ONLY public.refresh_tokens ADD CONSTRAINT ukk67ke3il4jxwu6wpqldns594d UNIQUE (usuario_id);
ALTER TABLE ONLY public.refresh_tokens ADD CONSTRAINT fkpdrw1klic7bvvhhkjojwu64t2 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

-- Tabla verification_tokens
CREATE TABLE IF NOT EXISTS public.verification_tokens (
    id bigint NOT NULL,
    fecha_expiracion timestamp(6) with time zone NOT NULL,
    token character varying(6) NOT NULL,
    type character varying(20) NOT NULL,
    usuario_id bigint,
    CONSTRAINT verification_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['VERIFY_EMAIL'::character varying, 'RESET_PASSWORD'::character varying])::text[])))
);

ALTER TABLE public.verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_tokens_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.verification_tokens ADD CONSTRAINT verification_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.verification_tokens ADD CONSTRAINT uk6q9nsb665s9f8qajm3j07kd1e UNIQUE (token);
ALTER TABLE ONLY public.verification_tokens ADD CONSTRAINT fko5b151r82btbdhtiv0iqxxuki FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

-- Tabla reservas
CREATE TABLE IF NOT EXISTS public.reservas (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    estado character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone,
    fecha_reserva date NOT NULL,
    hora_fin time(0) without time zone NOT NULL,
    hora_inicio time(0) without time zone NOT NULL,
    monto_total numeric(10,2) NOT NULL,
    paletas boolean NOT NULL,
    pelotas boolean NOT NULL,
    cancha_id integer NOT NULL,
    cliente_id bigint NOT NULL,
    created_by_id bigint NOT NULL,
    CONSTRAINT reservas_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'SEÑADA'::character varying, 'PARCIALMENTE_PAGADA'::character varying, 'PAGADA'::character varying, 'CANCELADA'::character varying, 'EXPIRADA'::character varying, 'COMPLETADA'::character varying])::text[])))
);

ALTER TABLE public.reservas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.reservas ADD CONSTRAINT reservas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reservas ADD CONSTRAINT fk9ga67qjqyhc60u0f10tf7ssgo FOREIGN KEY (cliente_id) REFERENCES public.usuarios(id);
ALTER TABLE ONLY public.reservas ADD CONSTRAINT fkhsisrsj6ak1fxmid9h3pj39x6 FOREIGN KEY (created_by_id) REFERENCES public.usuarios(id);
ALTER TABLE ONLY public.reservas ADD CONSTRAINT fkmc85ps4j27fo6uuek0iviq1c9 FOREIGN KEY (cancha_id) REFERENCES public.canchas(id);

-- Tabla pagos
CREATE TABLE IF NOT EXISTS public.pagos (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    estado character varying(255) NOT NULL,
    external_payment_id character varying(255),
    monto numeric(10,2) NOT NULL,
    paid_at timestamp(6) without time zone,
    preference_id character varying(255),
    provider character varying(255) NOT NULL,
    reserva_id bigint NOT NULL,
    CONSTRAINT pagos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying, 'EN_PROCESO'::character varying, 'DEVUELTO'::character varying, 'EXPIRADO'::character varying])::text[]))),
    CONSTRAINT pagos_provider_check CHECK (((provider)::text = ANY ((ARRAY['MERCADO_PAGO'::character varying, 'MANUAL'::character varying])::text[])))
);

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.pagos ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pagos ADD CONSTRAINT fkrd490715qtq2imjqrn0rwyhsl FOREIGN KEY (reserva_id) REFERENCES public.reservas(id);